import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import Navbar from "@/components/layout/Navbar";
import { Providers } from "@/providers/providers";
const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Rashid Visda",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon.ico", sizes: "any" },
    ],
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} antialiased  font-onest`}>
        <Providers>
          <div className="min-h-screen custom-container ">
            {/* lg screen 20/80 grid */}
            <div className="hidden lg:grid lg:grid-cols-[20%_80%] min-h-screen mt-8">
              <Sidebar />
              <main className="p-6">{children}</main>
            </div>

            {/* mobile navbar  */}
            <div className="lg:hidden flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-1 p-4">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
